# Generated by Django 4.2.2 on 2023-07-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyClass',
            new_name='Post',
        ),
    ]
